---
- name: Deploy RHEL7 on VMware
  hosts: localhost
  gather_facts: false
  vars:
    vsphere_vcenter_hostname: "vcenter.example.com"
    vsphere_vcenter_username: "root"
    vsphere_vcenter_password: "r3dh4t1!"
    vsphere_datacenter_name: "DC01"
    vsphere_esxi_host: "172.16.0.30"
    vsphere_datastore_name: "vsphere1-datastore"
    vsphere_template_name: "rhel7.1"
  roles:
    - vsphere

...
