---
- name: Deploy RHEL7 on VMware
  hosts: localhost
  vars:
    vsphere_vcenter_hostname: "vcenter1"
    vsphere_vcenter_username: "root"
    vsphere_vcenter_password: "r3dh4t1!"
    vsphere_datacenter_name: "DC01"
    vsphere_esxi_host: "esxi1"
    vsphere_datastore_name: "vsphere1-datastore"
    vsphere_template_name: "rhel7-vmw"

  roles:
    - vsphere

...